# Generated by Django 4.1 on 2022-09-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodcate_name', models.CharField(max_length=150)),
                ('foodcate_des', models.TextField()),
                ('foodcate_img', models.ImageField(null=True, upload_to='food_categories')),
            ],
        ),
    ]
