# Generated by Django 4.1 on 2022-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default=' ', max_length=50)),
                ('food_quantity', models.IntegerField(default=' ', max_length=20)),
                ('customer_email', models.CharField(default=' ', max_length=100)),
                ('customer_Mobile', models.IntegerField(default=' ', max_length=15)),
                ('message', models.TextField(default=' ')),
            ],
        ),
    ]
