# Generated by Django 4.1 on 2022-10-10 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_orderform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(default='', max_length=150)),
                ('sub_price', models.FloatField(default='', max_length=50)),
                ('sub_image', models.ImageField(null=True, upload_to='sub_cate')),
                ('foodcate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.food_categories')),
            ],
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
